#!/usr/bin/env python3
"""
WeEvolve Skill Export — Generate portable skill.md from knowledge base.
========================================================================
The protocol rides on existing products. skill.md IS the distribution mechanism.

'weevolve skill export' generates a skill file any AI agent can read.
'weevolve skill export --topic ai_engineering' generates domain-specific.
"""

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from weevolve.config import WEEVOLVE_DB, EVOLUTION_STATE_PATH


def _load_state() -> dict:
    """Load evolution state safely."""
    try:
        with open(EVOLUTION_STATE_PATH) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {"level": 1, "xp": 0, "skills": {}}


def _get_db():
    """Open the WeEvolve database read-only."""
    if not WEEVOLVE_DB.exists():
        return None
    return sqlite3.connect(str(WEEVOLVE_DB))


def export_skill(
    topic: Optional[str] = None,
    output_path: Optional[str] = None,
    limit: int = 20,
    min_quality: float = 0.6,
    verbose: bool = True,
) -> str:
    """Generate a portable skill.md from the knowledge base.

    Args:
        topic: Filter to a specific skill category (e.g. 'ai_engineering')
        output_path: Where to write the file. Default: ~/.weevolve/skill.md
        limit: Max number of learnings to include
        min_quality: Minimum quality threshold
        verbose: Print progress

    Returns:
        Path to the generated skill.md
    """
    state = _load_state()
    db = _get_db()

    if not db:
        if verbose:
            print("  No knowledge base found. Learn something first!")
            print("  Try: weevolve learn --text 'your first insight'")
        return ""

    # Query learnings
    if topic:
        rows = db.execute("""
            SELECT title, learn, question, expand, improve, quality, skills
            FROM knowledge_atoms
            WHERE quality >= ? AND skills LIKE ?
            ORDER BY quality DESC
            LIMIT ?
        """, (min_quality, f'%"{topic}"%', limit)).fetchall()
    else:
        rows = db.execute("""
            SELECT title, learn, question, expand, improve, quality, skills
            FROM knowledge_atoms
            WHERE quality >= ?
            ORDER BY quality DESC
            LIMIT ?
        """, (min_quality, limit)).fetchall()

    if not rows:
        if verbose:
            print(f"  No learnings found above quality {min_quality}")
        return ""

    # Build skill.md content
    topic_label = topic or "general"
    skills = state.get("skills", {})
    level = state.get("level", 1)

    lines = [
        f"---",
        f"name: weevolve-{topic_label}",
        f"version: 1.0.0",
        f"description: Knowledge distilled through SEED protocol",
        f"source: WeEvolve Level {level}",
        f"generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        f"atoms: {len(rows)}",
        f"min_quality: {min_quality}",
        f"protocol: SEED (8-phase recursive learning)",
        f"---",
        f"",
        f"# WeEvolve Skill: {topic_label.replace('_', ' ').title()}",
        f"",
        f"Distilled from {len(rows)} knowledge atoms processed through the SEED protocol.",
        f"Each insight has been perceived, connected, questioned, and improved.",
        f"",
    ]

    # Top skills section
    if skills:
        sorted_skills = sorted(skills.items(), key=lambda x: x[1], reverse=True)
        top_5 = sorted_skills[:5]
        lines.append("## Skill Profile")
        lines.append("")
        for skill_name, val in top_5:
            lines.append(f"- **{skill_name}**: {val:.0f}/100")
        lines.append("")

    # Learnings section
    lines.append("## Key Learnings")
    lines.append("")

    for i, (title, learn, question, expand, improve, quality, skills_json) in enumerate(rows, 1):
        alpha_tag = " *" if quality >= 0.9 else ""
        lines.append(f"### {i}. {title or 'Untitled'}{alpha_tag}")
        lines.append("")
        if learn:
            lines.append(f"**Learn:** {learn}")
            lines.append("")
        if question:
            lines.append(f"**Question:** {question}")
            lines.append("")
        if expand:
            lines.append(f"**Opportunity:** {expand}")
            lines.append("")
        if improve:
            lines.append(f"**Action:** {improve}")
            lines.append("")
        lines.append(f"*Quality: {quality:.1f}/1.0*")
        lines.append("")

    # Integration instructions
    lines.extend([
        "## How to Use This Skill",
        "",
        "This skill.md was generated by WeEvolve — the agent that evolves itself.",
        "",
        "**For AI agents:** Read this file to inherit the distilled knowledge.",
        "**For humans:** Each learning is an actionable insight. Start with #1.",
        "**To evolve further:** `pip install weevolve` and run `weevolve learn`.",
        "",
        "## SEED Protocol",
        "",
        "Every insight was processed through 8 phases:",
        "PERCEIVE -> CONNECT -> LEARN -> QUESTION -> EXPAND -> SHARE -> RECEIVE -> IMPROVE",
        "",
        "Phase 8 (IMPROVE) is the lever: most systems learn. This one learns how to learn.",
        "",
        f"---",
        f"*Generated by WeEvolve v0.1.0 | Level {level} | {len(rows)} atoms*",
    ])

    content = "\n".join(lines)

    # Write to file
    if output_path:
        out = Path(output_path)
    else:
        from weevolve.config import get_data_dir
        out = get_data_dir() / f"skill-{topic_label}.md"

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)

    if verbose:
        print(f"  Skill exported: {out}")
        print(f"  Atoms: {len(rows)} | Quality: >={min_quality}")
        print(f"  Topic: {topic_label}")
        print(f"  Share this file with any AI agent to transfer knowledge.")

    return str(out)


def list_exportable_topics(verbose: bool = True) -> list:
    """Show which topics have enough learnings to export."""
    db = _get_db()
    if not db:
        return []

    rows = db.execute("""
        SELECT skills FROM knowledge_atoms WHERE quality >= 0.6
    """).fetchall()

    topic_counts = {}
    for (skills_json,) in rows:
        try:
            for s in json.loads(skills_json or "[]"):
                topic_counts[s] = topic_counts.get(s, 0) + 1
        except (json.JSONDecodeError, TypeError):
            pass

    sorted_topics = sorted(topic_counts.items(), key=lambda x: x[1], reverse=True)

    if verbose and sorted_topics:
        print(f"\n  Exportable Topics:")
        for topic_name, count in sorted_topics:
            exportable = "ready" if count >= 5 else "growing"
            print(f"    {topic_name:<20} {count} atoms ({exportable})")
        print()

    return sorted_topics
